apiVersion: v1
kind: Service
metadata:
  name: my-kuard-svc
  labels:
    app: kuard
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: kuard
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-kuard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        ports:
        - containerPort: 8080